version: '3'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: uwsr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    networks:
      - my-network

  java_project:
    image: tomcat:jdk17
    container_name: tomcat-container
    ports:
      - "8081:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
